// <auto-generated />
using System;
using Hunt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HuntRepository.Migrations
{
    [DbContext(typeof(HuntContext))]
    partial class HuntContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hunt.Model.Animal", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Identifier");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Hunt.Model.Club", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Identifier");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Hunt.Model.Hunting", b =>
                {
                    b.Property<Guid>("Identifier");

                    b.Property<DateTime>("Issued");

                    b.Property<bool>("Status");

                    b.HasKey("Identifier");

                    b.ToTable("Huntings");
                });

            modelBuilder.Entity("Hunt.Model.PartialHuntersList", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("HunterNumber");

                    b.Property<Guid?>("PartialHuntingIdentifier");

                    b.Property<Guid>("UserIdentifier");

                    b.HasKey("Identifier");

                    b.HasIndex("PartialHuntingIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("PartialHuntersList");
                });

            modelBuilder.Entity("Hunt.Model.PartialHunting", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("HuntingIdentifier");

                    b.Property<bool>("Status");

                    b.HasKey("Identifier");

                    b.HasIndex("HuntingIdentifier");

                    b.ToTable("PartialHunting");
                });

            modelBuilder.Entity("Hunt.Model.Role", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Identifier");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Hunt.Model.Score", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AnimalIdentifier");

                    b.Property<Guid?>("HuntingIdentifier");

                    b.Property<DateTime?>("Issued");

                    b.Property<int>("Quantity");

                    b.Property<Guid?>("UserIdentifier");

                    b.HasKey("Identifier");

                    b.HasIndex("AnimalIdentifier");

                    b.HasIndex("HuntingIdentifier");

                    b.HasIndex("UserIdentifier");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("Hunt.Model.User", b =>
                {
                    b.Property<Guid>("Identifier")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<DateTime>("Issued");

                    b.Property<string>("Login");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Surname");

                    b.HasKey("Identifier");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hunt.Model.Hunting", b =>
                {
                    b.HasOne("Hunt.Model.User", "Leader")
                        .WithOne()
                        .HasForeignKey("Hunt.Model.Hunting", "Identifier")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hunt.Model.PartialHuntersList", b =>
                {
                    b.HasOne("Hunt.Model.PartialHunting")
                        .WithMany("PartialHunters")
                        .HasForeignKey("PartialHuntingIdentifier");

                    b.HasOne("Hunt.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentifier")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hunt.Model.PartialHunting", b =>
                {
                    b.HasOne("Hunt.Model.Hunting", "Hunting")
                        .WithMany("PartialHuntings")
                        .HasForeignKey("HuntingIdentifier")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hunt.Model.Score", b =>
                {
                    b.HasOne("Hunt.Model.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalIdentifier");

                    b.HasOne("Hunt.Model.Hunting", "Hunting")
                        .WithMany()
                        .HasForeignKey("HuntingIdentifier");

                    b.HasOne("Hunt.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserIdentifier");
                });
#pragma warning restore 612, 618
        }
    }
}
